version: "3.8"

services:
  blog:
    container_name: "bh_blog"
    build:
      context: .
      dockerfile: blog/Dockerfile
    command: python -m blog
    restart: always
    ports:
      - "81:80"
    volumes:
      - "./src:/opt/src:ro"
      - "./blog:/opt/blog:ro"
      - "./templates:/opt/templates:ro"
      - "./static:/opt/static:ro"
    env_file:
      - ".env"
    depends_on:
      - db

  profile:
    container_name: "bh_profile"
    build:
      context: .
      dockerfile: profile/Dockerfile
    command: python -m profile
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./src:/opt/src:ro"
      - "./profile:/opt/profile:ro"
      - "./templates:/opt/templates:ro"
      - "./static:/opt/static:ro"
    environment:
      SESSION_STORAGE_URL: redis://bh:6379/0
    env_file:
      - ".env"
    depends_on:
      - db
      - redis

  migrations:
    container_name: "bh_migrations"
    build:
      context: .
      dockerfile: migrations/Dockerfile
    command: python -m migrations
    volumes:
      - ".:/opt:rw"
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    container_name: "bh_db"
    image: postgres:16-alpine3.19
    hostname: "bh"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin

  celery:
    container_name: "bh_celery"
    build:
      context: .
      dockerfile: blog/Dockerfile
    command: celery -A src.config:celery worker -l INFO --concurrency=10
    restart: always
    volumes:
      - "./src:/opt/src:ro"
      - "./blog:/opt/blog:ro"
      - "./templates:/opt/templates:ro"
      - "./static:/opt/static:ro"
    env_file:
      - ".env"
    depends_on:
      - db
      - celery_beat

  celery_beat:
    container_name: "bh_celery_beat"
    build:
      context: .
      dockerfile: blog/Dockerfile
    command: celery -A src.config:celery beat -l INFO
    restart: always
    volumes:
      - "./src:/opt/src:ro"
      - "./blog:/opt/blog:ro"
      - "./templates:/opt/templates:ro"
      - "./static:/opt/static:ro"
    env_file:
      - ".env"
    depends_on:
      - db

  redis:
    container_name: "bh_redis"
    hostname: "bh"
    restart: always
    image: redis:7.2.2-alpine3.18
